version: "3"

services:
  redis:
    image: redis:6.2.7
    ports:
      - "16379:6379"
    restart: always

  mysql:
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: "x"
    ports:
      - "13306:3306"
    restart: always
